local this = {}

this.ON_BATTLE_ROUND_BEGIN = "ON_BATTLE_ROUND_BEGIN"

this.ON_SELECT_OP_UNIT = "ON_SELECT_OP_UNIT"
this.ON_REQ_SELECT_CARD = "ON_SELECT_CARD"
this.ON_CARD_SELECTED = "ON_CARD_SELECTED"
this.ON_REQ_UNSELECT_CARD = "ON_REQ_UNSELECT_CARD"
this.ON_CANCEL_SELECT = "ON_CANCEL_SELECT"
this.ON_CARD_UNSELECTED = "ON_CARD_UNSELECTED"
this.ON_DROP_SELECT = "ON_DROP_SELECT"
this.ON_CARD_DROPED = "ON_CARD_DROPED"
this.ON_REFRESH_BATTLE_UI = "ON_REFRESH_BATTLE_UI"

this.ON_CREATE_UNIT = "ON_CREATE_UNIT"

this.ON_INPUT_ORDER = "ON_INPUT_ORDER"
this.ON_PLAYCARD_READY_CHANGE = "ON_PLAYCARD_READY_CHANGE"
this.ON_CONFIRM_PLAYCARD = "ON_CONFIRM_PLAYCARD"

-- unit event
--this.ON_DROP_CARD

-- notify csharp message
this.ON_PERFORM_START = "ON_PERFORM_START"
this.ON_SHOW_CARD_DETAIL = "ON_SHOW_CARD_DETAIL"
this.REQ_PLAYCARD_PARAMS = "REQ_PLAYCARD_PARAMS"
this.ON_QUIT_PALYCARD = "ON_QUIT_PALYCARD"

return this
