local this = {}

this.ON_BATTLE_ROUND_BEGIN = "ON_BATTLE_ROUND_BEGIN"

this.ON_SELECT_OP_UNIT = "ON_SELECT_OP_UNIT"
this.ON_SELECT_CARD = "ON_SELECT_CARD"

this.ON_CREATE_UNIT = "ON_CREATE_UNIT"

this.ON_INPUT_CS_ORDER = "ON_INPUT_CS_ORDER"
this.REQ_PLAYCARD_PARAMS = "REQ_PLAYCARD_PARAMS"
this.ON_PLAYCARD_READY_CHANGE = "ON_PLAYCARD_READY_CHANGE"
this.ON_CONFIRM_PLAYCARD = "ON_CONFIRM_PLAYCARD"
this.ON_CANCEL_PLAYCARD = "ON_CANCEL_PLAYCARD";

return this
